
package View;

/**
 *
 * @author cn3
 */
public class ViewTelaPrincipal extends javax.swing.JFrame {
/**
 * @author Diego Mansoldo and Gabriel Vital
 */
    public ViewTelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        MenuSair = new javax.swing.JMenu();
        jMenuSaida = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        MenuCadCliente = new javax.swing.JMenuItem();
        MenuPesCliente = new javax.swing.JMenuItem();
        MenuEditProduto = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        MenuPesProduto = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        MenuRelSintetico = new javax.swing.JMenuItem();
        MenuRelAnalitico = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        MenuVender = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela Principal");

        MenuSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/page.png"))); // NOI18N
        MenuSair.setText("Arquivo");

        jMenuSaida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/door_out.png"))); // NOI18N
        jMenuSaida.setText("Sair");
        jMenuSaida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSaidaActionPerformed(evt);
            }
        });
        MenuSair.add(jMenuSaida);

        jMenuBar1.add(MenuSair);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/group.png"))); // NOI18N
        jMenu2.setText("Clientes");

        MenuCadCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/group_add.png"))); // NOI18N
        MenuCadCliente.setText("Cadastrar");
        MenuCadCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCadClienteActionPerformed(evt);
            }
        });
        jMenu2.add(MenuCadCliente);

        MenuPesCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/zoom_in.png"))); // NOI18N
        MenuPesCliente.setText("Pesquisar");
        MenuPesCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuPesClienteActionPerformed(evt);
            }
        });
        jMenu2.add(MenuPesCliente);

        jMenuBar1.add(jMenu2);

        MenuEditProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/computer.png"))); // NOI18N
        MenuEditProduto.setText("Produtos");

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/computer_add.png"))); // NOI18N
        jMenuItem1.setText("Cadastrar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        MenuEditProduto.add(jMenuItem1);

        MenuPesProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/zoom_in.png"))); // NOI18N
        MenuPesProduto.setText("Pesquisar");
        MenuPesProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuPesProdutoActionPerformed(evt);
            }
        });
        MenuEditProduto.add(MenuPesProduto);

        jMenuBar1.add(MenuEditProduto);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/report.png"))); // NOI18N
        jMenu4.setText("Relatórios");
        jMenu4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu4ActionPerformed(evt);
            }
        });

        MenuRelSintetico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/report_add.png"))); // NOI18N
        MenuRelSintetico.setText("Relatório Sintatico");
        MenuRelSintetico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuRelSinteticoActionPerformed(evt);
            }
        });
        jMenu4.add(MenuRelSintetico);

        MenuRelAnalitico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/report_add.png"))); // NOI18N
        MenuRelAnalitico.setText("Relatório Analitico");
        MenuRelAnalitico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuRelAnaliticoActionPerformed(evt);
            }
        });
        jMenu4.add(MenuRelAnalitico);

        jMenuBar1.add(jMenu4);

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/money.png"))); // NOI18N
        jMenu5.setText("Vender");

        MenuVender.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/money_add.png"))); // NOI18N
        MenuVender.setText("Vender");
        MenuVender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuVenderActionPerformed(evt);
            }
        });
        jMenu5.add(MenuVender);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 726, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 361, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    //Fecha o Sistema
    private void jMenuSaidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSaidaActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuSaidaActionPerformed
    //Inicializa a Tela de Cadastro de Cliente
    private void MenuCadClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCadClienteActionPerformed
      ViewCliente cliente = new ViewCliente();
      cliente.setVisible(true);
    }//GEN-LAST:event_MenuCadClienteActionPerformed
    //Inicializa a tela de Pesquisa de Cliente
    private void MenuPesClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuPesClienteActionPerformed
        ViewClientePesquisar clienteP = new ViewClientePesquisar();
        clienteP.setVisible(true);        
    }//GEN-LAST:event_MenuPesClienteActionPerformed

    private void jMenu4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu4ActionPerformed
        
    }//GEN-LAST:event_jMenu4ActionPerformed

    private void MenuVenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuVenderActionPerformed
        ViewVender venda = new ViewVender();
        venda.setVisible(true);
    }//GEN-LAST:event_MenuVenderActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        ViewProduto telaProduto = new ViewProduto();
        telaProduto.setVisible(true);
    
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void MenuRelSinteticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuRelSinteticoActionPerformed
        ViewRelatorioSintetico sintetico = new ViewRelatorioSintetico();
        sintetico.setVisible(true);
    }//GEN-LAST:event_MenuRelSinteticoActionPerformed

    private void MenuRelAnaliticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuRelAnaliticoActionPerformed
        ViewRelatorioAnalitico analitico = new ViewRelatorioAnalitico();
        analitico.setVisible(true);
    }//GEN-LAST:event_MenuRelAnaliticoActionPerformed

    private void MenuPesProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuPesProdutoActionPerformed
        ViewProdutoPesquisa telaPesquisa = new ViewProdutoPesquisa();
        telaPesquisa.setVisible(true);
    }//GEN-LAST:event_MenuPesProdutoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewTelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewTelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewTelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewTelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ViewTelaPrincipal().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuCadCliente;
    private javax.swing.JMenu MenuEditProduto;
    private javax.swing.JMenuItem MenuPesCliente;
    private javax.swing.JMenuItem MenuPesProduto;
    private javax.swing.JMenuItem MenuRelAnalitico;
    private javax.swing.JMenuItem MenuRelSintetico;
    private javax.swing.JMenu MenuSair;
    private javax.swing.JMenuItem MenuVender;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuSaida;
    // End of variables declaration//GEN-END:variables
}
